dist: trusty

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y linux-headers-$(uname -r)
  - sudo apt-get install libnuma-dev
  - sude apt-get install bash

script:
  - bash .buildtest.sh
